
[build-system]
requires = [
  "setuptools >= 40.9.0",
  "wheel",
]
build-backend = "setuptools.build_meta"
# https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html#using-a-src-layout
